define('Controls/List/Swipe/Constants', [

], function(

) {
   'use strict';

   return {
      ACTION_ICON_CLASS: 'controls-itemActionsV__action_icon icon-size',
      SMALL_ICON_SIZE: 24,
      BIG_ICON_SIZE: 32,
      TITLE_HEIGHT: 16,
      VERTICAL_MARGIN: 12,
      ROW_FIRST_TYPE_THRESHOLD: 38,
      ROW_SECOND_TYPE_THRESHOLD: 46,
      ROW_THIRD_TYPE_THRESHOLD: 54,
      ROW_FOURTH_TYPE_THRESHOLD: 73,
      COLUMN_FIRST_TYPE_THRESHOLD: 24,
      COLUMN_SECOND_TYPE_THRESHOLD: 32,
      COLUMN_THIRD_TYPE_THRESHOLD: 40,
      COLUMN_FOURTH_TYPE_THRESHOLD: 48,
      SEPARATOR_WIDTH: 1,
      TWO_COLUMN_MENU_TYPE: 13,
      ROW_TYPE_THRESHOLD: 4,
      ONE_COLUMN_TYPE_THRESHOLD: 8,
      SUBTYPE_COUNT: 4,
      TYPES_WITH_TITLE: [3, 4, 7, 8, 11, 12]
   };
});
